name: ez_store
description: Ez Store
version: 1.0.0+1
publish_to: none

## Generate Localizations
## flutter pub run easy_localization:generate --source-dir ./assets/translations -f keys -o locale_keys.g.dart


environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^7.2.0
  intl: ^0.17.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_native_splash: ^2.1.3+1
  easy_localization: ^3.0.1

  ## Network
  retrofit: ^3.0.1
  logger: ^1.0.0  #for logging purpose
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  synchronized: ^3.0.0
  retry: ^3.1.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

  ## Data format & Json format
  json_serializable: ^6.3.2
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  easy_mask: ^2.0.1

  #####  View
  flutter_rating_bar: ^4.0.1
  scroll_to_index: ^3.0.1
  loader_overlay: ^2.1.0
  breakpoint: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.3
  velocity_x: ^3.3.0
  like_button: ^2.0.2
  photo_view: ^0.13.0
  flutter_local_notifications: ^9.4.0
  flutter_reaction_button: ^2.0.0+1
  share_plus: ^6.1.0
  #  flutter_html: ^3.0.0-alpha.3
  #  flutter_html_all: ^3.0.0-alpha.3
  flutter_math_fork: ^0.6.1
  tab_indicator_styler: ^2.0.0
  readmore: ^2.1.0
  introduction_screen: ^3.0.2
  modal_bottom_sheet: ^3.0.0-pre
  infinite_scroll_pagination: ^3.1.0
  visibility_detector: ^0.3.3
  flutter_staggered_grid_view: ^0.6.1
  screenshot: ^1.2.3
  expandable_page_view: ^1.0.14
  ensure_visible_when_focused: ^1.1.1
  flutter_switch: ^0.3.2

  ## Form
  reactive_forms: ^13.0.0
  #  reactive_raw_autocomplete: ^0.1.1
  #  flutter_typeahead: ^3.2.5
  reactive_flutter_typeahead: ^0.4.0
  reactive_range_slider: ^0.4.0

  ## Loading process
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  pull_to_refresh: 2.0.0
  custom_refresh_indicator: ^1.1.1
  stop_watch_timer: ^1.3.1

  ## Animation
  animate_do: ^2.1.0
  scrollable_positioned_list: ^0.3.2
  animations: ^2.0.3

  ## WebView
  webview_flutter: ^4.0.2
  #  flutter_webview_plugin: ^0.4.0
  #  flutter_inappwebview: ^5.4.3+7

  ## Navigation
  auto_route: ^5.0.1
  uni_links: ^0.5.1

  #####  Data
  hive: ^2.0.2
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  timeago: ^3.2.2
  url_launcher: ^6.1.0
  email_validator: ^2.0.1
  flutter_multi_formatter: ^2.6.2

  #####  Resource & Config
  flutter_keyboard_visibility: ^5.1.0
  connectivity_plus: ^2.2.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.0+1
  image_picker: ^0.8.5+3
  file_picker: ^5.2.2
  package_info_plus: ^1.3.0
  device_info_plus: ^8.0.0
  permission_handler: ^9.2.0
  path: ^1.8.1
  path_provider: ^2.0.10
  android_path_provider: ^0.3.0
  #  audioplayers: ^1.0.1
  just_audio: ^0.9.28
  open_file: ^3.2.1
  antdesign_icons: ^0.0.3
  flutter_phosphor_icons: ^0.0.1+6


  #####  Firebase
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.4
  firebase_auth: ^4.0.1
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  firebase_crashlytics: ^3.0.1
  crypto: ^3.0.2
  sign_in_with_apple: ^4.1.0
  firebase_dynamic_links: ^5.0.4

  #  firebase_analytics: ^8.3.4
  #  firebase_remote_config: ^0.11.0+2

  ##### Google Service
  google_place: ^0.4.7
  google_maps_flutter: ^2.1.4
  map_launcher: ^2.4.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4

  #####  Environment
  #  flutter_flavor: ^3.1.1

  #####  CLI
  mason_cli: ^0.1.0-dev.30

  #####  Testing
  #  mockito: ^5.1.0

  #package internal import
  logger_and_error:
    path: ./packages/logger_and_error
  app_ui:
    path: ./packages/app_ui
  app_ui_kit:
    path: ./packages/app_ui_kit
  app_utils:
    path: ./packages/app_utils
  app_values:
    path: ./packages/app_values

dependency_overrides:
  webview_flutter: ">=3.0.4"
  flutter_svg: ">=1.1.1+1"
  ffi: ">=2.0.1"
#  flutter_inappwebview: ">=5.4.3+7"

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.3.3
  retrofit_generator: ^4.0.1
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  test: ^1.19.5
  change_app_package_name: ^1.1.0
  flutter_flavorizr: ^2.1.4
  very_good_analysis: ^3.1.0
  freezed: ^2.2.0
  pub_version_plus: ^1.0.2

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: false
    null_safety: true

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/icons/
    - assets/icons/profile/
    - assets/icons/product/
    - assets/translations/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100

targets:
  $default:
    builders:
      hive_generator:
        enabled: false
        generate_for:
          - lib/data/**.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/data/**.dart
        exclude:
          - lib/data/**_extend.dart
          - lib/data/**_api.dart
          - lib/data/**_repo.dart
      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/features/**_bloc.dart
            - lib/features/**_cubit.dart
      mockito:mockBuilder:
        enabled: false
      auto_route_generator|autoRouteGenerator:
        enabled: true
        generate_for:
          include:
            - lib/features/routes/app_auto_route.dart
