include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [ bricks/** ]
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false