name: app_ui
description: UI Toolkit for the Base Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  tab_indicator_styler: ^2.0.0
  velocity_x: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.4

  app_values:
    path: ../app_values

flutter:
