name: app_ui_kit
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  velocity_x: ^3.3.0
  infinite_scroll_pagination: ^3.1.0
  custom_refresh_indicator: ^1.1.1
  pull_to_refresh: 2.0.0
  flutter_linkify: ^5.0.2
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.1
  scroll_to_index: ^3.0.1

  app_ui:
    path: ../app_ui
  app_values:
    path: ../app_values
  app_utils:
    path: ../app_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: