/// Flutter icons AppIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcon
///      fonts:
///       - asset: fonts/AppIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcon {
  AppIcon._();

  static const _kFontFam = 'AppIcon';
  static const String? _kFontPkg = null;

  static const IconData coupon = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_fill = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
